### ISSUE TITLE
希望支持json配置

### ISSUE THREAD

**Issue by lxhao61** [clevergo/caddy-dnspodcn#1]
因为caddy2很多特色功能仅支持json配置，希望caddy-dnspodcn插件能支持json配置，这样才能共同使用，且json配置DNS API启用更灵活。

**Comment by lxhao61** [comment]
Caddyfile转化为json，示例如下：
json example:
          "issuers": [{
            "module": "acme",
            "challenges": {
              "dns": {
                "provider": {
                  "Language": "en",
                  "BaseURL": "https://dnsapi.cn",
                  "name": "dnspodcn",
                  "AppID": "APP_ID",
                  "AppToken": "APP_TOKEN"
                }
              }
            }
          }]
        }]
      }
    }
  }
}

**Comment by razonyang** [comment]
Closed by #2
